- name: Install all necessary tools for KVM
  hosts: all
  become: true

  tasks:
    - name: Gather system facts
      ansible.builtin.setup:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install KVM and related packages
      ansible.builtin.apt:
        name:
          - qemu-kvm
          - libvirt-daemon-system
          - libvirt-clients
          - bridge-utils
          - virt-manager
        state: present

    - name: Enable and start libvirtd service
      ansible.builtin.systemd:
        name: libvirtd
        enabled: true
        state: started
