- name: Gather system information
  hosts: all
  become: true
  tasks:
    - name: Gather system facts
      ansible.builtin.setup:

    - name: Import KVM availability playbook
      import_playbook: kvm_availability.yml

    # You can add more tasks here, they will be skipped if kvm_availability fails
    - name: Continue with other tasks if KVM is available
      debug:
        msg: "KVM is available, continuing with the rest of the playbook."