---
- name: Check for KVM availability
  hosts: all
  become: true
  tasks:
    - name: Check if CPU supports hardware virtualization
      ansible.builtin.command: grep -E 'vmx|svm' /proc/cpuinfo
      register: cpu_vt_support
      changed_when: false
      failed_when: cpu_vt_support.rc != 0

    - name: Check if KVM module is loaded
      ansible.builtin.command: 
      cmd: |
       set -o pipefail # <-- adding this will prevent surprises
       lsmod | grep kvm
      executable: /bin/bash
      register: kvm_module
      changed_when: false
      failed_when: kvm_module.rc != 0

    - name: Verify KVM availability
      ansible.builtin.debug:
        msg: "KVM is available"
      when: cpu_vt_support.rc == 0 and kvm_module.rc == 0

    - name: Report KVM unavailability
      ansible.builtin.debug:
        msg: "KVM is not available"
      when: cpu_vt_support.rc != 0 or kvm_module.rc != 0
